apiVersion: v1
kind: Pod
metadata:
  name: test-delete-pod

spec:
  containers:
   - name: test
     image: busybox
     command: ["sleep", "3600"]

     volumeMounts: 
      - name: test-storage
        mountPath: /data

  volumes:
    - name: test-storage
      persistentVolumeClaim:
        claimName: test-delete-pvc